"""empty message

Revision ID: 725061a99504
Revises: 
Create Date: 2023-10-29 16:45:23.723739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725061a99504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
